---
  - name: "MAC OS Setup"
    hosts: localhost
    vars:
      date: "{{ lookup('pipe', 'date +%Y%m%d-%H%M') }}"
    vars_files:
    - variables.yml
    connection: local 
    roles:
        - role: gantsign.oh-my-zsh
          become: yes 
          become_user: "{{ USER }}"
          users:
            - username: "{{ USER }}"
              oh_my_zsh:
                theme: robbyrussell
                plugins:
                  - git
                  - direnv

    tasks:
    - name: copy keybindings to system folder 
      copy:
        src: keybindings/DefaultKeyBinding.dict
        dest: "/Users/{{ USER }}/Library/KeyBindings/"
      tags:
        - simple_copy


    - name: Clone linuxify
      ansible.builtin.git:
        repo: 'https://github.com/fabiomaia/linuxify.git'
        dest: "{{ LINUXIFY_TMP_PATH }}"
        version: master

    - name: Run linuxify
      shell: "cd {{ LINUXIFY_TMP_PATH }} && echo 'n' | ./linuxify install "
      
 
    - community.general.homebrew:
        name: "{{ item }}"
        state: present
      with_list:                       
        - gettext
        - gpgme
        - podman
        - node
        - "go@{{ GO_VERSION }}"
        - azure-cli
        - direnv
        - jq
        - pstree
        - python3        
        - virtualenv        
        - gh
        - direnv
        - azure-cli

    - community.general.homebrew:
        name: "{{ item }}"
        state: linked
      with_list:
        - gettext   

    - community.general.homebrew:
        name: "{{ item }}"
        state: linked
        install_options: overwrite,force
      with_list:
        - "go@{{ GO_VERSION }}"


    - homebrew_cask:
        name: "{{ item }}"
        state: present
      with_list:
        - visual-studio-code
        - iterm2
        - rectangle

    - name: Register file
      stat:
        path: "/usr/local/bin/podman"
      register: podman_path

    - name: Docker == Podman
      ansible.builtin.file:
        src: /usr/local/bin/podman
        dest: /usr/local/bin/docker   
        state: link
      when: podman_path.stat.exists == True

    - name: zshrc
      lineinfile: 
        state: present
        dest: /Users/Uli/.zshrc
        regexp: './linuxify'
        line: '.  ~/.linuxify'

    - name: zshrc
      lineinfile: 
        state: present
        dest: /Users/Uli/.zshrc
        regexp: 'direnv hook zsh'
        line: 'eval "$(direnv hook zsh)"'  

    - name: Copy .zshrc file with backup
      copy:
        src: /Users/Uli/.zshrc
        dest: /Users/Uli/.zshrc-uli-{{ date }}
     
    - name: cleanup
      ansible.builtin.file:
        path: "{{ LINUXIFY_TMP_PATH }}"
        state: absent
      when: CLEANUP_LINUXIFY_TMP_FOLDER|bool
        

    - name: Reminder
      debug: 
        msg: 
          - "    "
          - "    "
          - "        --------------------------------------   "
          - "    "
          - "     >>>> Don't forget to adapt your PATH  <<<<< "
          - "    "
          - "        --------------------------------------   "
          - "    "
          - "    "
    



